export const experts = [
  {
    id: 1,
    image: "/images/experts/expert-1.jpg",
    name: "Dr. John Carter",
    role: "Lead Sports Scientist",
    experience: "12+ Years",
    specialties: [
      "Performance Testing",
      "Biomechanics",
      "Athlete Monitoring",
    ],
    linkedin: "#",
  },
  {
    id: 2,
    image: "/images/experts/expert-2.jpg",
    name: "Dr. Sarah Mitchell",
    role: "Senior Physiotherapist",
    experience: "10+ Years",
    specialties: [
      "Rehabilitation",
      "Manual Therapy",
      "Return To Sport",
    ],
    linkedin: "#",
  },
  {
    id: 3,
    image: "/images/experts/expert-3.jpg",
    name: "Alex Williams",
    role: "Strength & Conditioning Coach",
    experience: "8+ Years",
    specialties: [
      "Strength",
      "Speed",
      "Power",
    ],
    linkedin: "#",
  },
  {
    id: 4,
    image: "/images/experts/expert-4.jpg",
    name: "Emily Brown",
    role: "Performance Analyst",
    experience: "6+ Years",
    specialties: [
      "GPS Analysis",
      "Load Monitoring",
      "Recovery",
    ],
    linkedin: "#",
  },
  {
    id: 5,
    image: "/images/experts/expert-5.jpg",
    name: "David Wilson",
    role: "Sports Nutritionist",
    experience: "9+ Years",
    specialties: [
      "Nutrition",
      "Supplements",
      "Hydration",
    ],
    linkedin: "#",
  },
  {
    id: 6,
    image: "/images/experts/expert-6.jpg",
    name: "Sophia Lee",
    role: "Biomechanics Expert",
    experience: "11+ Years",
    specialties: [
      "Movement Analysis",
      "Running Mechanics",
      "Injury Prevention",
    ],
    linkedin: "#",
  },
];